apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 5
  strategy:
    canary:
      stableService: rollouts-ingress-stable
      canaryService: rollouts-ingress-canary
      trafficRouting:
        nginx:
          stableIngress: rollouts-ingress-stable
          additionalIngressAnnotations:
            canary-by-header: User-Agent
            canary-by-header-value: Firefox
#          header: "User-Agent=Firefox"
      steps:
        - setWeight: 0
          pause: {}
        - setWeight: 100
          pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:green
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rollouts-ingress-stable
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: demo.rollouts.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rollouts-demo
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rollouts-ingress-canary
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary-by-header: "User-Agent=Firefox"
spec:
  rules:
    - host: demo.rollouts.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rollouts-demo-canary
                port:
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-ingress-stable
spec:
  selector:
    app: rollouts-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-ingress-canary
spec:
  selector:
    app: rollouts-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
