apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 6
  selector:
    matchLabels:
      app: alb-rollout
  template:
    metadata:
      labels:
        app: alb-rollout
    spec:
      containers:
        - name: alb-rollout
          image: "argoproj/rollouts-demo:green"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
  strategy:
    canary:
      scaleDownDelaySeconds: 60
      stableService: stable-service
      canaryService: canary-service
      trafficRouting:
        managedRoutes:
          - name: header-route
        alb:
          ingress: alb-rollout-ingress
          rootService: rollouts-demo-stable #action1
          servicePort: 8080
      steps:
        - setHeaderRoute:
            name: header-route
            match:
              - headerName: Custom-Header
                headerValue:
                  exact: Mozilla*
        - setWeight: 100
        - pause: {}
