apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-canary-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.15.4
          ports:
            - containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      steps:
        - setCanaryScale:
          replicas: 1
        - pause: {}
