apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 2
  strategy:
    canary:
      stableService: rollouts-ingress-stable
      canaryService: rollouts-ingress-canary
      trafficRouting:
        nginx:
          stableIngress: rollouts-ingress
          additionalIngressAnnotations:
            canary-by-header: User-Agent
            canary-by-header-value: Firefox
      steps:
        - setCanaryScale:
            matchTrafficWeight: true
        - pause: {}
        - setWeight: 100
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - name: rollouts-demo
          image: timam/canary-poc:003
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rollouts-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/canary: "true"
#    nginx.ingress.kubernetes.io/canary-by-header: "User-Agent"
#    nginx.ingress.kubernetes.io/canary-by-header-value: "Firefox"
spec:
  rules:
    - host: demo.rollouts.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rollouts-ingress-stable
                port:
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-ingress-stable
spec:
  selector:
    app: rollouts-demo
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-ingress-canary
spec:
  selector:
    app: rollouts-demo
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
