name: Deploy pokemon API

on:
  push:
    branches:
      - main

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './api'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{secrets.GHCR_USER}}
          password: ${{secrets.GHCR_TOKEN}}

      - name: Build & Push Docker Image
        run: |
          docker build . --tag ghcr.io/${{secrets.GHCR_USER}}/pokemons-api:${{ github.sha }}
          docker push ghcr.io/${{secrets.GHCR_USER}}/pokemons-api:${{ github.sha }}



